// ignore_for_file: avoid_print, always_specify_types, prefer_final_locals, avoid_catches_without_on_clauses
import 'dart:io';

void main() {
  final dir = Directory('lib');
  if (!dir.existsSync()) return;

  int setStateCount = 0;
  int valueNotifierCount = 0;
  int repaintBoundaryCount = 0;
  int transactionCount = 0;
  int incrementCount = 0;
  List<String> thoughts = [];

  for (var entity in dir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.dart')) {
      try {
        final lines = entity.readAsLinesSync();
        for (int i = 0; i < lines.length; i++) {
          final line = lines[i].trim();
          
          if (line.contains('setState(')) setStateCount++;
          if (line.contains('ValueNotifier')) valueNotifierCount++;
          if (line.contains('RepaintBoundary')) repaintBoundaryCount++;
          if (line.contains('runTransaction') || line.contains('Transaction(')) transactionCount++;
          if (line.contains('FieldValue.increment')) incrementCount++;
          
          if (line.contains('// @AETHER:')) {
            thoughts.add('- **${entity.uri.pathSegments.last}** (Line ${i+1}): ${line.substring(line.indexOf('// @AETHER:') + 11).trim()}');
          }
        }
      } catch (_) {
      }
    }
  }

  final telemetryFile = File('AETHER_TELEMETRY.md');
  StringBuffer output = StringBuffer('# Aether Automated Telemetry Report\n\n');
  output.writeln('> Auto-generated by the pre-commit "Flight Recorder".\n');
  
  output.writeln('## 1. Architectural Fingerprint');
  if (transactionCount > 0 || incrementCount > 0) {
    output.writeln('✅ Atomic operations detected (`runTransaction`: $transactionCount, `increment`: $incrementCount)');
  } else {
    output.writeln('❌ No atomic operations detected.');
  }

  output.writeln('\n### UI Performance');
  output.writeln('- `setState`: $setStateCount | `ValueNotifier`: $valueNotifierCount | `RepaintBoundary`: $repaintBoundaryCount');
  
  if (valueNotifierCount > 0 || repaintBoundaryCount > 0) {
    output.writeln('✅ Targeted repaints detected.');
  } else if (setStateCount > 3) {
    output.writeln('⚠️ High `setState` usage without localized rebuilds.');
  }

  output.writeln('\n## 2. Developer Thought Log');
  if (thoughts.isNotEmpty) {
    thoughts.forEach(output.writeln);
  } else {
    output.writeln('*No inline `// @AETHER:` comments found.*');
  }

  try {
    telemetryFile.writeAsStringSync(output.toString());
  } catch (_) {
  }
}
